Presentation/Plugin.Web/Plugins/MyPlugin/Models/ConfigureViewModel.cs
namespace MyPlugin.Models
{
    public class ConfigureViewModel
    {
        public bool CallToMyPlugin { get; set; }
        public string Message { get; set; }
    }
}

Presentation/Plugin.Web/Plugins/MyPlugin/Controllers/MyPluginController.cs
using Microsoft.AspNetCore.Mvc;
using MyPlugin.Models;

namespace MyPlugin.Controllers
{
    [Route("[controller]")]
    public class MyPluginController : Controller
    {
        [HttpGet]
        public IActionResult Configure()
        {
            return View("~/Plugins/MyPlugin/Views/Configure.cshtml", new ConfigureViewModel());
        }

        [HttpPost]
        public IActionResult Configure(ConfigureViewModel model)
        {
            var configureView = new ConfigureViewModel();
            if (model.CallToMyPlugin) 
            {
                configureView.Message = "Hello! Welcome from MyPlugin!";

                return Json(new { Message = configureView.Message });
            }

            return View("~/Plugins/MyPlugin/Views/Configure.cshtml", configureView);
        }
    }
}

Presentation/Plugin.Web/Plugins/MyPlugin/Views/Configure.cshtml
@model MyPlugin.Models.ConfigureViewModel

<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

<h1>Welcome to the Plugin Configuration Page</h1>

<form id="configureForm" method="post" enctype="multipart/form-data">
    <button type="submit">Click Me</button>
</form>

<div id="message">
    @Model.Message
</div>

<script type="text/javascript">
    $("#configureForm").submit(function (event) {
        event.preventDefault();
        $.ajax({
            url: "@Url.Action("Configure", "MyPlugin")",
            type: "POST",
            data: {
                CallToMyPlugin: true
            },
            success: function (data) {
                $("#message").text(data.message);
            }
        });
    });
</script>